// react_project/src/components/Key/index.tsx
import type { Vectors } from "@common/types/output";
import KeyCore from "./core";
type Props = {
	rowVectors: Vectors;
	keyVectors: Vectors;
	color?: string;
};

export const Key = ({ rowVectors, keyVectors, color }: Props) => {
	return (
		<KeyCore
			position={rowVectors.pos.add(keyVectors.pos).toVector3().toArray()}
			rotation={rowVectors.dir.add(keyVectors.dir).toVector3().toArray()}
			color={color}
		/>
	);
};

// vue_project/src/components/Preview/Key/index.vue
<script setup lang="ts">
import type { Vectors } from "@common/types/output";
import Key from "./core.vue";

type Props = {
  rowVectors: Vectors;
  keyVectors: Vectors;
};

defineProps<Props>();
</script>

<template>
  <Key
    :position="rowVectors.pos.add(keyVectors.pos).toVector3().toArray()"
    :rotation="rowVectors.dir.add(keyVectors.dir).toVector3().toArray()"
  />
</template>
