// react_project/src/components/Col.tsx
import type { Col } from "@common/types/output";
import type { MeshProps } from "@react-three/fiber";
import { Key } from "./Key";

type Props = MeshProps & {
	col: Col;
};
// eslint-disable-next-line react-refresh/only-export-components
export default ({ col, ...props }: Props) => (
	<>
		<Key
			rowVectors={col.homeRowVector}
			keyVectors={col.perRow.numRow}
			{...props}
		/>
		<Key
			rowVectors={col.homeRowVector}
			keyVectors={col.perRow.upper}
			{...props}
		/>
		<Key
			rowVectors={col.homeRowVector}
			keyVectors={col.perRow.home}
			// color={keyPrimaryColor}
			{...props}
		/>
		<Key
			rowVectors={col.homeRowVector}
			keyVectors={col.perRow.bottom}
			{...props}
		/>
	</>
);

// src/components/Preview/Col.vue
<script setup lang="ts">
import type { Col } from "../../types/output";
import Key from "./Key.vue";

type Props = {
  col: Col;
};

defineProps<Props>();
</script>

<template>
  <Key
    :position="col.homeRowVector.pos.add(col.perRow.numRow.pos).toVector3().toArray()"
    :rotation="col.homeRowVector.dir.add(col.perRow.numRow.dir).toVector3().toArray()"
  />
  <Key
    :position="col.homeRowVector.pos.add(col.perRow.upper.pos).toVector3().toArray()"
    :rotation="col.homeRowVector.dir.add(col.perRow.upper.dir).toVector3().toArray()"
  />
  <Key
    :position="col.homeRowVector.pos.add(col.perRow.home.pos).toVector3().toArray()"
    :rotation="col.homeRowVector.dir.add(col.perRow.home.dir).toVector3().toArray()"
    color="#090909"
  />
  <Key
    :position="col.homeRowVector.pos.add(col.perRow.bottom.pos).toVector3().toArray()"
    :rotation="col.homeRowVector.dir.add(col.perRow.bottom.dir).toVector3().toArray()"
  />
</template>
