// vue_project/src/components/Preview/Col.vue
<script setup lang="ts">
import type { Col } from "@common/types/output";
import Key from "./Key/index.vue";

type Props = {
  col: Col;
};

defineProps<Props>();
</script>

<template>
  <Key :rowVectors="col.homeRowVector" :keyVectors="col.perRow.numRow" />
  <Key :rowVectors="col.homeRowVector" :keyVectors="col.perRow.upper" />
  <Key :rowVectors="col.homeRowVector" :keyVectors="col.perRow.home" />
  <Key :rowVectors="col.homeRowVector" :keyVectors="col.perRow.bottom" />
</template>

// react_project/src/components/Col.tsx
import type { Col } from "@common/types/output";
import type { MeshProps } from "@react-three/fiber";
import { Key } from "./Key";

type Props = MeshProps & {
	col: Col;
};
// eslint-disable-next-line react-refresh/only-export-components
export default ({ col, ...props }: Props) => (
	<>
		<Key
			rowVectors={col.homeRowVector}
			keyVectors={col.perRow.numRow}
			{...props}
		/>
		<Key
			rowVectors={col.homeRowVector}
			keyVectors={col.perRow.upper}
			{...props}
		/>
		<Key
			rowVectors={col.homeRowVector}
			keyVectors={col.perRow.home}
			// color={keyPrimaryColor}
			{...props}
		/>
		<Key
			rowVectors={col.homeRowVector}
			keyVectors={col.perRow.bottom}
			{...props}
		/>
	</>
);
