// vue_project/src/components/Preview/Key/core.vue
<script setup lang="ts">
import { keySize, keySubColor } from "@common/constant";

type Props = {
  position: [number, number, number];
  rotation: [number, number, number];
  color?: string;
};

defineProps<Props>();
</script>

<template>
  <TresMesh :position="position" :rotation="rotation">
    <TresBoxGeometry :args="[keySize, 1, keySize]" />
    <TresMeshStandardMaterial :color="color ?? keySubColor" />
  </TresMesh>
</template>

// react_project/src/components/Key/core.tsx
import { keySize, keySubColor } from "@common/constant";
import type { MeshProps } from "@react-three/fiber";
import { extend } from "@react-three/fiber";
import { Mesh } from "three";

extend({ Mesh });
type Props = MeshProps & {
	position: [number, number, number];
	rotation: [number, number, number];
	color?: string;
};

// eslint-disable-next-line react-refresh/only-export-components
export default ({ position, rotation, color, ...props }: Props) => {
	return (
		<mesh position={position} {...props} rotation={rotation}>
			<boxGeometry args={[keySize, 1, keySize]} />
			<meshStandardMaterial color={color ?? keySubColor} />
		</mesh>
	);
};
